// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { SidebarProvider } from "../context/SidebarContext";
// import Navbar from "@/app/components/Navbar";
// import Sidebar from "@/app/components/Sidebar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Next.js with MUI",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <SidebarProvider>
//           <div style={{ display: "flex" }}>
//             <Navbar />
//             <Sidebar />
//             <main style={{ flexGrow: 1, padding: "24px", marginTop: "64px" }}>
//               {children}
//             </main>
//           </div>
//         </SidebarProvider>
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
// app/layout.tsx

// app/layout.tsx
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js Dashboard",
  description: "Next.js Dashboard with Firebase Auth",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
